Repository SWE-574-GROUP-1/SWE574-GROUP-1, pull requests merged in 2023-05, with the labels that each got.

#115 53 enhancement space name description avatar features
  SWE574/core/migrations/0019_space_avatar_space_description.py
  SWE574/core/migrations/0020_subscriber_space_subscribers.py
  SWE574/core/models.py
  SWE574/core/templates/base_inside.html
  SWE574/core/templates/navbar.html
  SWE574/core/templates/post_container.html
  SWE574/core/templates/post_create_modal.html
  SWE574/core/templates/search.html
  SWE574/core/templates/sidebar.html
  SWE574/core/templates/spaces.html
  SWE574/core/templates/spaces_search.html
  SWE574/core/templates/tags.html
  SWE574/core/urls.py
  SWE574/core/views.py
  SWE574/images/space_images/default_space.jpg
Labels: Frontend, Backend, Enhancement

#117 #116: space bug fixed
  SWE574/core/migrations/0021_alter_profile_background_image.py
  SWE574/core/models.py
  SWE574/core/src/models/post_model_handler.py
  SWE574/core/templates/base_inside.html
  SWE574/core/templates/navbar.html
  SWE574/core/templates/post_container.html
  SWE574/core/templates/post_create_modal.html
  SWE574/core/templates/post_edit_modal.html
  SWE574/core/templates/sidebar.html
  SWE574/core/templates/spaces.html
  SWE574/core/tests/test_profile_model.py
  SWE574/core/views.py
Labels: Bug, Frontend, Backend

#121 New About Page - Ertan
  SWE574/core/templates/about.html
  SWE574/core/templates/navbar.html
  SWE574/core/templates/signin.html
  SWE574/core/templates/signup.html
  SWE574/core/urls.py
  SWE574/core/views.py
Labels: Frontend

#129 #57: feature bookmark categories and able to list and filter
  SWE574/core/migrations/0023_bookmark_label_name_profile_available_labels_and_more.py
  SWE574/core/models.py
  SWE574/core/src/models/post_model_handler.py
  SWE574/core/src/models/profile_model_handler.py
  SWE574/core/src/pages/profile_page_handler.py
  SWE574/core/templates/base_inside.html
  SWE574/core/templates/bookmark_modal.html
  SWE574/core/templates/debookmark_modal.html
  SWE574/core/templates/post_container.html
  SWE574/core/templates/profile.html
  SWE574/core/tests/test_profile_model.py
  SWE574/core/urls.py
  SWE574/core/views.py
  SWE574/images/space_images/test_2.png
Labels: New Feature Request, Important - Takes Time, Frontend, Backend

#132 #130: bug migration merge problem
  SWE574/core/migrations/0023_bookmark_label_name_profile_available_labels_and_more.py
  SWE574/core/migrations/0024_alter_profile_background_image.py
Labels: Bug

#134 #133: bug search keyword a
  SWE574/core/views.py
  deliverables/uml_class_diagram.png
Labels: Bug, Important - Quick Fix, Backend

#126 Feature add comment
  SWE574/core/admin.py
  SWE574/core/forms.py
  SWE574/core/migrations/0024_comment_post_comments.py
  SWE574/core/models.py
  SWE574/core/templates/post_container.html
  SWE574/core/urls.py
  SWE574/core/views.py
Labels: New Feature Request, Frontend, Backend

#139 #138: frontend bugs in space and bookmarks are fixed.
  SWE574/core/admin.py
  SWE574/core/models.py
  SWE574/core/src/controllers/annotation_controller.py
  SWE574/core/templates/base_inside.html
  SWE574/core/templates/bookmark_modal.html
  SWE574/core/templates/debookmark_modal.html
  SWE574/core/templates/post_container.html
  SWE574/core/templates/post_create_modal.html
  SWE574/core/templates/post_edit_modal.html
  SWE574/core/templates/profile.html
  SWE574/core/views.py
Labels: Bug, Important - Takes Time, Frontend, Backend
